### PR TITLE
For `open` print path to `STDOUT`

### PR DESCRIPTION
**Pull request by mikekaminsky**

### CODE REVIEW

**Comment by jgillies** [comment]
@mikekaminsky I think to get exactly what I was shooting for, there needs to be an option to avoid opening the file in an external text editor, and to only output the filename. I think some sort of handling could occur [here](https://github.com/mikekaminsky/dbt-helper/blob/9e7d859b3c97550d7ae1ff2c9f57458e32a71632/core/open.py#L113-L115) (maybe just pull out my ` with open...` code and use `pass`, unless that's a terrible way to write Python).

Also, it's sort of unrelated, but I'm wondering if `--print` is the best name for this option. Because `--print` is a fairly common option among CLI tools, it might be better reserved for more widely used `dbt-helper` functionality down the road. And if it's not printing the code, it doesn't really describe what's going on anyway.

**Comment by mikekaminsky** [comment]
@jgillies the way i have it implemented here (now actually working :) ) is that the `--print` option will still print to the terminal, but after it prints the path. I _think_ this will still work for your use-case although of course you're relying on the ordering of print statements in this code which is ... fragile.

I think if we wanted to do this correctly, we'd refactor this into two commands, one for getting the path to the model, and another for printing or opening it (that uses the code from the first).

**Comment by mikekaminsky** [comment]
@jgillies would love to know if you can make this work with your vim setup as-is :)

**Comment by mikekaminsky** [comment]
Closing in favor of https://github.com/mikekaminsky/dbt-helper/pull/23

**Pull request closed without merging**
