### PR TITLE
Feature/add print model

### PR DESCRIPTION
**Pull request by jgillies**
@mikekaminsky This is more what I had in mind, and also why I'm not sure that `print` is the best name to use for this option.

### CODE REVIEW

**Comment by mikekaminsky** [comment]
So my thought was this: we can print the path _always_ and then use the print _flag_ to indicate that you want to print the contents of the file to stdout rather than opening in a text editor. My hope was that `open my_model -p` would still work for use case in that world. Does that make sense?

**Comment by jgillies** [comment]
Yeah, that makes sense. But to be able to directly open the compiled file in Vim, I think I need to be able to print _only_ the path, and  _not_ attempt to open the file in an external editor. So maybe what I'm actually looking for is an option to suppress the opening of the compiled file.

**Comment by mikekaminsky** [comment]
@jgillies the `-p` flag in this pr https://github.com/mikekaminsky/dbt-helper/pull/21 would do that! Instead of opening with an editor, it prints to stdout, so should work for you. I think!

**Comment by mikekaminsky** [comment]
After a slack conversation, we're going to refactor this a bit so that returning the path to the file is its own subcommand. PR forthcoming this weekend, closing this in the meantime.

**Pull request closed without merging**
